package main

import (
	"fmt"
	"path/filepath"
)

// OpenCodeProjector generates OpenCode platform files.
// OpenCode reads .claude/ dirs natively, so projectClaudeDir handles shared output.
// It also has its own .opencode/ directory for native skills/agents.
type OpenCodeProjector struct{}

func (p *OpenCodeProjector) Name() string { return "opencode" }

func (p *OpenCodeProjector) OutputPaths(rules, skills, agents []string, hasMCP bool) []string {
	// OpenCode shares .claude/ directory + has its own .opencode/
	paths := []string{"AGENTS.md", ".opencode/plugins/lore-hooks.mjs"}
	for _, n := range rules {
		paths = append(paths, ".claude/rules/"+n+".md")
	}
	for _, n := range skills {
		paths = append(paths, ".claude/skills/"+n+"/", ".claude/skills/"+n+"/SKILL.md")
		paths = append(paths, ".opencode/skills/"+n+"/", ".opencode/skills/"+n+"/SKILL.md")
	}
	for _, n := range agents {
		paths = append(paths, ".claude/agents/"+n+".md")
		paths = append(paths, ".opencode/agents/"+n+".md")
	}
	return paths
}

func (p *OpenCodeProjector) Project(root string, ms *MergedSet) error {
	// Shared .claude/ directory — OpenCode reads these natively
	if err := projectClaudeDir(root, ms); err != nil {
		return err
	}

	// Also project to .opencode/ native directories
	opencodeDir := filepath.Join(root, ".opencode")
	if err := projectSkills(opencodeDir, ms); err != nil {
		return err
	}
	if err := projectAgentsRecord(opencodeDir, ms); err != nil {
		return err
	}

	// AGENTS.md at root (OpenCode mandate file)
	if err := writeAGENTSMD(root, ms); err != nil {
		return err
	}

	// Hooks: OpenCode uses JS plugins, not JSON config.
	// Generate a stub plugin that shells out to `lore hook`.
	return p.writeHookPlugin(root)
}

func (p *OpenCodeProjector) writeHookPlugin(root string) error {
	plugin := `// Lore hook plugin for OpenCode
// Generated by lore generate — do not edit manually.
import { execSync } from "child_process";

function loreHook(name, ctx) {
  try {
    const input = JSON.stringify(ctx);
    execSync("lore hook " + name, { input, stdio: ["pipe", "pipe", "inherit"] });
  } catch (_) {}
}

export default {
  name: "lore-hooks",

  hooks: {
    "tool.execute.before": (ctx) => loreHook("pre-tool-use", ctx),
    "tool.execute.after": (ctx) => loreHook("post-tool-use", ctx),
    "chat.message": (ctx) => loreHook("prompt-submit", ctx),
    "stop": (ctx) => loreHook("stop", ctx),
    "experimental.session.compacting": (ctx) => loreHook("pre-compact", ctx),
  },

  event: (event) => {
    if (event.type === "session.created") loreHook("session-start", event);
    if (event.type === "session.deleted") loreHook("session-end", event);
  },
};
`
	path := filepath.Join(root, ".opencode", "plugins", "lore-hooks.mjs")
	if err := writeFile(path, []byte(plugin)); err != nil {
		return fmt.Errorf("write opencode hook plugin: %w", err)
	}
	return nil
}
